spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopsn?useSSL=false
    username: root
    password: 123456

second:
  datasource:
      url: jdbc:mysql://localhost:3306/test?useSSL=false
      username: root
      password: 123456
    
    
